# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 985952a3f91d0f942fb39ced86c9809b4fe039412ddb0728e6cd645ccae9b8c25b8afeb514f49fea095798545c648541b20d320625c1f2b854b04a88a76aba34

test:
  secret_key_base: b8842c6285ad43146d0cc60134b2007a6e80491ad74252a74f393df82d61b3ae9682688211460a87e5542c5fb0184c0a713e94b803fb61e2b6157d80eec818d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
